### ISSUE TITLE
Start the program

### ISSUE THREAD

**Issue by lSyrexl** [kmvi/javascript-deobfuscator#4]
How do I open a .ts file with npm?

**Comment by lSyrexl** [comment]
Because if I do
node index.ts
I get this error: 
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
